In [7]:
import numpy as np

x_data=np.array([1, 2, 3, 4, 5]).reshape(5,1)
y_data=np.array([3, 5, 7, 9, 11]).reshape(5,1)   # y=2x+1
print(x_data)
print(y_data)

[[1]
 [2]
 [3]
 [4]
 [5]]
[[ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]]


In [8]:
w=np.random.rand(1,1)
b=np.random.rand(1)
print(w,b)

[[0.49411025]] [0.94035678]


In [9]:
def loss_func(x, t):
  y=np.dot(x,w)+b
  return (np.sum((t-y)**2))/(len(x))

In [10]:
# 수치미분 – 다변수
def numerical_derivative(f,x):
  delta_x=1e-4
  grad=np.zeros_like(x)

  it=np.nditer(x,flags=['multi_index'], op_flags=['readwrite'])

  while not it.finished:
    idx=it.multi_index
    tmp_val=x[idx]
    x[idx]=float(tmp_val)+delta_x
    fx1=f(x)
    x[idx]=tmp_val-delta_x
    fx2=f(x)

    grad[idx]=(fx1-fx2)/(2*delta_x)

    x[idx]=tmp_val
    it.iternext()

  return grad

In [11]:
def predict(x):
  y=np.dot(x, w)+b
  return y

In [12]:
learning_rate=1e-2
f=lambda x: loss_func(x_data, y_data)
print("Initial error value=", loss_func(x_data, y_data),"Initial w=", w, "b=",b)

for step in range(20000):
  w-=learning_rate*numerical_derivative(f, w)
  b-=learning_rate*numerical_derivative(f,b)

  if step % 100==0:
    print('step:',step, 'error value:',loss_func(x_data, y_data),
           'w=',w, 'b=',b)

Initial error value= 25.48719731759802 Initial w= [[0.49411025]] b= [0.94035678]
step: 0 error value: 15.001205375306947 w= [[0.82898459]] b= [1.01181057]
step: 100 error value: 0.005713402280902626 w= [[1.95091553]] b= [1.17716715]
step: 200 error value: 0.0028715080222550308 w= [[1.9652022]] b= [1.12560034]
step: 300 error value: 0.0014431958256211235 w= [[1.97533056]] b= [1.08904272]
step: 400 error value: 0.0007253381063011537 w= [[1.98251092]] b= [1.06312568]
step: 500 error value: 0.00036454884299987804 w= [[1.98760134]] b= [1.04475212]
step: 600 error value: 0.0001832191880973739 w= [[1.99121014]] b= [1.03172643]
step: 700 error value: 9.208442580920587e-05 w= [[1.99376854]] b= [1.02249204]
step: 800 error value: 4.628085936121949e-05 w= [[1.99558229]] b= [1.01594544]
step: 900 error value: 2.326037138625748e-05 w= [[1.99686812]] b= [1.01130431]
step: 1000 error value: 1.1690467387471685e-05 w= [[1.99777969]] b= [1.00801404]
step: 1100 error value: 5.875530767249312e-06 w= [[1.9

step: 1300 error value: 1.4841492091256436e-06 w= [[1.99920889]] b= [1.00285545]
step: 1400 error value: 7.459209330466538e-07 w= [[1.99943915]] b= [1.00202433]
step: 1500 error value: 3.748935989291132e-07 w= [[1.9996024]] b= [1.00143513]
step: 1600 error value: 1.8841837558287047e-07 w= [[1.99971812]] b= [1.00101741]
step: 1700 error value: 9.469749379189297e-08 w= [[1.99980017]] b= [1.00072128]
step: 1800 error value: 4.7594165392644034e-08 w= [[1.99985833]] b= [1.00051134]
step: 1900 error value: 2.3920427972397065e-08 w= [[1.99989957]] b= [1.00036251]
step: 2000 error value: 1.2022206286500584e-08 w= [[1.9999288]] b= [1.000257]
step: 2100 error value: 6.042259952930065e-09 w= [[1.99994952]] b= [1.00018219]
step: 2200 error value: 3.0367891274942373e-09 w= [[1.99996421]] b= [1.00012916]
step: 2300 error value: 1.5262647215493903e-09 w= [[1.99997463]] b= [1.00009157]
step: 2400 error value: 7.670878360356518e-10 w= [[1.99998201]] b= [1.00006492]
step: 2500 error value: 3.85531906677

In [13]:
predict(np.array([7]))

array([15.])