In [14]:
import numpy as np
x_data1 = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
t_data1 = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

x_data=np.array(x_data1)
t_data=np.array(t_data1)
print(x_data.shape, t_data.shape)
print(x_data)
print(t_data)

(5, 3) (5, 1)
[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]]
[[152.]
 [185.]
 [180.]
 [196.]
 [142.]]


In [15]:
w=np.random.rand(3,1)
b=np.random.rand(1)
print(w)
print(b)

[[0.13416823]
 [0.47049467]
 [0.51773049]]
[0.90886167]


In [16]:
def loss_func(x,t):
  y=np.dot(x, w)+b
  return (np.sum((t-y)**2))/(len(x))

In [17]:
def predict(x):
  y=np.dot(x,w)+b
  return y

In [18]:
def numerical_derivative(f,x):
    delta_x=1e-4
    grad=np.zeros_like(x)

    it=np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    
    while not it.finished:
        idx=it.multi_index
        tmp_val=x[idx]
        
        x[idx]=float(tmp_val)+delta_x
        fx1=f(x) # f(x+delta_x)

        x[idx]=float(tmp_val)-delta_x
        fx2=f(x) # f(x-delta_x)

        grad[idx]=(fx1-fx2)/(2*delta_x)

        x[idx]=tmp_val
        it.iternext()

    return grad

In [22]:
learning_rate=1e-5
f=lambda x: loss_func(x_data, t_data)
print('Initail error value:',loss_func(x_data, t_data), "w:",w, "b:",b)

for step in range(200001):
  w-=learning_rate*numerical_derivative(f, w)
  b-=learning_rate*numerical_derivative(f, b)

  if step % 400==0:
    print("s:",step,'err', loss_func(x_data, t_data), 'w:',w, 'b:',b)

Initail error value: 0.1406673577815523 w: [[0.99469097]
 [0.49801927]
 [0.50764745]] b: [1.05240648]
s: 0 err 0.14066735311834871 w: [[0.99469096]
 [0.49801926]
 [0.50764746]] b: [1.05240669]
s: 400 err 0.1406654878883265 w: [[0.99468594]
 [0.49801701]
 [0.50765366]] b: [1.05249267]
s: 800 err 0.14066362275418914 w: [[0.99468093]
 [0.49801476]
 [0.50765985]] b: [1.05257865]
s: 1200 err 0.1406617577159261 w: [[0.99467591]
 [0.4980125 ]
 [0.50766605]] b: [1.05266462]
s: 1600 err 0.14065989277353433 w: [[0.99467089]
 [0.49801025]
 [0.50767225]] b: [1.05275059]
s: 2000 err 0.1406580279270019 w: [[0.99466587]
 [0.498008  ]
 [0.50767845]] b: [1.05283656]
s: 2400 err 0.14065616317632088 w: [[0.99466085]
 [0.49800574]
 [0.50768466]] b: [1.05292253]
s: 2800 err 0.14065429852148387 w: [[0.99465582]
 [0.49800349]
 [0.50769086]] b: [1.0530085]
s: 3200 err 0.14065243396248694 w: [[0.9946508 ]
 [0.49800123]
 [0.50769706]] b: [1.05309446]
s: 3600 err 0.14065056949931415 w: [[0.99464578]
 [0.49799897

In [25]:
predict(np.array([[80,85,100],[100,85,80]]))

array([[173.78102601],
       [183.40861126]])