In [310]:
# 2장 파이토치 기본.pdf
import torch

print(torch.tensor([1,2,3,4,5]))
print(torch.tensor([[1,2,3],[4,5,6]], dtype=torch.int64))
print(torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32))

tensor([1, 2, 3, 4, 5])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [311]:
ft=torch.FloatTensor([[1,2,3],[4,5,6]]);print(ft)
lt=torch.LongTensor([[1,2,3],[4,5,6]]);print(lt)
bt=torch.ByteTensor([[1,0],[0,1]]);print(bt)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 0],
        [0, 1]], dtype=torch.uint8)


In [312]:
import numpy as np
x=np.array([[1,2,3],[4,5,6]])
print(x,type(x), x.shape)

tx=torch.from_numpy(x)
print(tx, type(tx), tx.shape, tx.size())

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'> (2, 3)
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32) <class 'torch.Tensor'> torch.Size([2, 3]) torch.Size([2, 3])


In [313]:
nx=tx.numpy()
print(nx, type(nx), nx.shape)

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'> (2, 3)


In [314]:
print(ft.long())
print(lt.float())
print(bt.long())

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1, 0],
        [0, 1]])


In [315]:
x=torch.tensor([[[1,2],[3,4]], [[5,6],[7,8]], [[9,10],[11,12]]])

print(x.shape)
print(x.size())
# x의 차원계수
print('x.dim',x.dim())
# x의 사이즈 len
print('len(x.size())',len(x.size()))
print(x.size(0))
print(x.shape[0])
print(x.size(1))
print(x.shape[1])
print(x.size(2))
print(x.shape[2])
# 마지막위치 -1(리버스)
print(x.size(-1))
print(x.shape[-1])

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])
x.dim 3
len(x.size()) 3
3
3
2
2
2
2
2
2


In [316]:
# 기본 연산(+ - * / == != ** )
a=torch.FloatTensor([[1,2],[3,4]])
b=torch.FloatTensor([[2,2],[3,3]])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
print(a==b)
print(a!=b)
print(a**b)

tensor([[3., 4.],
        [6., 7.]])
tensor([[-1.,  0.],
        [ 0.,  1.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])
tensor([[0., 1.],
        [1., 1.]])
tensor([[False,  True],
        [ True, False]])
tensor([[ True, False],
        [False,  True]])
tensor([[ 1.,  4.],
        [27., 64.]])


In [317]:
print(a)
print(a+1)
print(a+torch.tensor([1,2]))

tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 3.],
        [4., 5.]])
tensor([[2., 4.],
        [4., 6.]])


In [318]:
print(a)
print(a.mul_(b))  # 언더바 붙이면 밑에 a 값 변화 = 인플레이스 현상
print(a)

tensor([[1., 2.],
        [3., 4.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])


In [319]:
# 인플레이스 연산(Inplace Operations)
print(b)
print(b.sum())
print(b.sum(dim=0))
print(b.sum(dim=-1))
print(b.mean())

tensor([[2., 2.],
        [3., 3.]])
tensor(10.)
tensor([5., 5.])
tensor([4., 6.])
tensor(2.5000)


In [320]:
x=np.arange(1,13).reshape(3,2,2)
# 3차원 tensor
tx=torch.from_numpy(x)

print(tx.view(3,4))
print(tx.view(2,3,2))
# -1은 모양을 잘 모를때
print(tx.view(3,-1))
print(tx.view(-1,3))

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]], dtype=torch.int32)
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]], dtype=torch.int32)


In [321]:
xx=tx.view(3,1,4)
xx

tensor([[[ 1,  2,  3,  4]],

        [[ 5,  6,  7,  8]],

        [[ 9, 10, 11, 12]]], dtype=torch.int32)

In [322]:
# Squeeze()함수 : 차원의 크기가 1인 차원 제거
# Unsqueeze()함수 : Squeeze() 반대 함수로 Unsqueeze()로 지정된 차원의 인덱스에 차원의 크기가 1인 차원 삽입
x1=tx.view(3,1,4)
x2=tx.view(2,3,1,2)
# 차원제거
print(x1.squeeze())
print(x2.squeeze())

print(x1.size())
x1.unsqueeze_(1)
x1.size()

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]], dtype=torch.int32)
torch.Size([3, 1, 4])


torch.Size([3, 1, 1, 4])

In [323]:
# 인덱싱 / 슬라이싱
tx.size()

# 3차원중 1번째 요소
print(tx[0])
# 3차원요소 1번째, 전부
print(tx[0,:])

print(tx[0,:,:])

print(tx[0,1,:])

print(tx[0,:,1])

print(tx[-1,:])

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([3, 4], dtype=torch.int32)
tensor([2, 4], dtype=torch.int32)
tensor([[ 9, 10],
        [11, 12]], dtype=torch.int32)


In [324]:
# split 함수()
# 텐서 자르기 split

# x=torch.FloatTensor(10,4)
# x 정수화
x=torch.arange(1,41).view(10,4)
# 스플릿 크기 4 dim=0은 2차원인데 크기 4로 자른다
splits=x.split(4,dim=0)
for s in splits:
  print(s.size())


torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


In [325]:
x1=torch.arange(1,41).view(4,10)
x1

splits1=x.split(3, dim=1)
for s in splits1:
  print(s.size())

torch.Size([10, 3])
torch.Size([10, 1])


In [326]:
# chunks() 함수
chunks = x.chunk(3, dim=0)
for c in chunks:
  print(c.size())

torch.Size([4, 4])
torch.Size([4, 4])
torch.Size([2, 4])


In [327]:
# Index_Select 함수
indice=torch.LongTensor([2,1])
y=x.index_select(dim=0, index=indice)
print(x)
print(y)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36],
        [37, 38, 39, 40]])
tensor([[ 9, 10, 11, 12],
        [ 5,  6,  7,  8]])


In [328]:
a
b

tensor([[2., 2.],
        [3., 3.]])

In [329]:
# Concatenate 함수(cat())
c=torch.cat([a,b], dim=1)
c

tensor([[ 2.,  4.,  2.,  2.],
        [ 9., 12.,  3.,  3.]])

In [330]:
# stack()함수
d=torch.stack([a,b])
print(d)
print(d.size())
print(a.size())
print(b.size())

tensor([[[ 2.,  4.],
         [ 9., 12.]],

        [[ 2.,  2.],
         [ 3.,  3.]]])
torch.Size([2, 2, 2])
torch.Size([2, 2])
torch.Size([2, 2])


In [331]:
aa=a.view(2,1,2)
print(aa)
print(aa.size())

# Expand 함수: 차원의 크기가 1인 차원을 원하는 크기로 늘려 줌
y=aa.expand(2,3,2)
y

tensor([[[ 2.,  4.]],

        [[ 9., 12.]]])
torch.Size([2, 1, 2])


tensor([[[ 2.,  4.],
         [ 2.,  4.],
         [ 2.,  4.]],

        [[ 9., 12.],
         [ 9., 12.],
         [ 9., 12.]]])

In [332]:
# Random Pernutation 함수
# 함수 명 : randperm(n) : 1~ n-1 범위의 숫자를 n개 랜덤 수열 생성

x=torch.randperm(100).view(-1,5,2)
x

tensor([[[54, 21],
         [92, 32],
         [52,  9],
         [20, 96],
         [ 2, 33]],

        [[44, 90],
         [49, 72],
         [86, 41],
         [64, 65],
         [27, 14]],

        [[28, 83],
         [84, 47],
         [63, 31],
         [69, 78],
         [71, 60]],

        [[ 4, 58],
         [12, 26],
         [98,  1],
         [89, 93],
         [34, 13]],

        [[40, 17],
         [55,  5],
         [11,  8],
         [37, 46],
         [39, 59]],

        [[95, 15],
         [ 6, 81],
         [75, 97],
         [85, 91],
         [19, 22]],

        [[25, 80],
         [10, 45],
         [76, 68],
         [56, 16],
         [18, 82]],

        [[30, 70],
         [24, 87],
         [ 3, 29],
         [57, 36],
         [51, 38]],

        [[23, 42],
         [99, 73],
         [53, 88],
         [ 0, 74],
         [62, 48]],

        [[67, 61],
         [50, 77],
         [66, 43],
         [94, 79],
         [35,  7]]])

In [333]:
x=torch.randperm(3**3).view(3,3,-1)
x

tensor([[[14,  7, 22],
         [15, 17, 21],
         [19, 26, 11]],

        [[ 4, 10, 25],
         [20, 24, 12],
         [ 2, 16,  1]],

        [[ 5, 13,  6],
         [18,  8, 23],
         [ 3,  0,  9]]])

In [334]:
# Argument Max 함수 : argmax(dim=n) (0:1차원, 1:2차원)
# 맨 마지막 값이 제일 큰 거
y=x.argmax(dim=-1)
print(y)
print(y.size())

tensor([[2, 2, 1],
        [2, 1, 1],
        [1, 2, 2]])
torch.Size([3, 3])


In [335]:
# Top-k 함수 : 가장 큰 k개 값과 index 반환
values,indices=torch.topk(x, k=2, dim=-1)
print(values)
print(values.size())
print(indices)
print(indices.size())

tensor([[[22, 14],
         [21, 17],
         [26, 19]],

        [[25, 10],
         [24, 20],
         [16,  2]],

        [[13,  6],
         [23, 18],
         [ 9,  3]]])
torch.Size([3, 3, 2])
tensor([[[2, 0],
         [2, 1],
         [1, 0]],

        [[2, 1],
         [1, 0],
         [1, 0]],

        [[1, 2],
         [2, 0],
         [2, 0]]])
torch.Size([3, 3, 2])


In [336]:
# Masked Fill 함수 : 텐서 내에 원하는 부분 값만 변경
# 1차원에서 가장 큰 k개의 값과 index 반환
value, indices=torch.topk(x,k=2,dim=-1)
print(value)
print(indices)
print(indices.size())

mask = x > 10
print(mask)

tensor([[[22, 14],
         [21, 17],
         [26, 19]],

        [[25, 10],
         [24, 20],
         [16,  2]],

        [[13,  6],
         [23, 18],
         [ 9,  3]]])
tensor([[[2, 0],
         [2, 1],
         [1, 0]],

        [[2, 1],
         [1, 0],
         [1, 0]],

        [[1, 2],
         [2, 0],
         [2, 0]]])
torch.Size([3, 3, 2])
tensor([[[ True, False,  True],
         [ True,  True,  True],
         [ True,  True,  True]],

        [[False, False,  True],
         [ True,  True,  True],
         [False,  True, False]],

        [[False,  True, False],
         [ True, False,  True],
         [False, False, False]]])


In [337]:
y=x.masked_fill(mask, value=0)
y

tensor([[[ 0,  7,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],

        [[ 4, 10,  0],
         [ 0,  0,  0],
         [ 2,  0,  1]],

        [[ 5,  0,  6],
         [ 0,  8,  0],
         [ 3,  0,  9]]])

In [339]:
# ones(), zeros(), ones_like(), zeros_like()
print(torch.ones(2,3))
print(torch.zeros(2,3))
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]])
tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]])
